# -*- coding: utf-8 -*-
"""
ScentWave — Fragrance Database Builder
Tier 1: 500+ hardcoded real perfumes (always available, no download)
Tier 2: Kaggle / HuggingFace dataset loader (10 000+ perfumes)
Tier 3: Live Fragrantica scraper (unlimited expansion)

Run:  python scripts/build_fragrance_db.py [--tier 1|2|3] [--kaggle path/to/csv]
"""

import json, csv, os, argparse, time, re
import urllib.request
from pathlib import Path

# ---------------------------------------------------------------------------
# TIER 1 — 500+ real perfumes (name, brand, family, top, middle, base, moods)
# ---------------------------------------------------------------------------
PERFUMES = [
    # ── CHANEL ──────────────────────────────────────────────────────────────
    ("Chanel No. 5",               "Chanel", "floral_aldehyde",
     "bergamot,neroli,ylang_ylang", "rose,jasmine,iris", "sandalwood,vetiver,vanilla,white_musk",
     "iconic,elegant,feminine,timeless,classic"),
    ("Chanel No. 19",              "Chanel", "green_floral",
     "galbanum,bergamot,neroli", "rose,iris,jasmine,lily_of_the_valley", "sandalwood,oakmoss,vetiver,civet",
     "green,powdery,classic,feminine,sophisticated"),
    ("Chanel Coco",                "Chanel", "oriental_spicy",
     "mandarin,bergamot,honey,coriander", "rose,jasmine,clove,cinnamon,clove", "sandalwood,vetiver,civet,amber,vanilla",
     "opulent,spicy,oriental,feminine,warm"),
    ("Chanel Coco Mademoiselle",   "Chanel", "oriental_floral",
     "orange,bergamot,mandarin,grapefruit", "rose,jasmine,ylang_ylang", "patchouli,vanilla,vetiver,white_musk",
     "youthful,confident,fresh,chic,modern"),
    ("Chanel Chance",              "Chanel", "floral",
     "pink_pepper,pineapple,grapefruit,hyacinth", "jasmine,iris,rose", "amber,patchouli,vetiver,white_musk",
     "fresh,youthful,spontaneous,feminine,modern"),
    ("Chanel Chance Eau Tendre",   "Chanel", "floral_fruity",
     "grapefruit,quince,pink_pepper", "jasmine,hyacinth", "amber,white_musk,iris,cedar",
     "delicate,tender,fresh,young,feminine"),
    ("Chanel Chance Eau Fraiche",  "Chanel", "floral_woody",
     "citron,water_hyacinth,pink_pepper", "jasmine,iris", "teak,white_musk,cedar,amber",
     "aquatic,fresh,modern,clean,feminine"),
    ("Chanel Allure",              "Chanel", "floral",
     "mandarin,pink_pepper,orange,aldehydes", "peach,magnolia,rose,jasmine,lily_of_the_valley", "vanilla,sandalwood,vetiver,amber",
     "elegant,timeless,sophisticated,feminine"),
    ("Chanel Allure Homme",        "Chanel", "aromatic_fougere",
     "lemon,bergamot,mandarin,aldehydes", "iris,nutmeg,star_anise,rose", "vanilla,tonka_bean,sandalwood,vetiver",
     "elegant,masculine,classic,fresh"),
    ("Chanel Allure Homme Sport",  "Chanel", "aromatic_aquatic",
     "mandarin,lemon,bergamot,grapefruit", "sea_notes,geranium,pepper,elemi", "amberwood,tonka_bean,white_musk,cedar",
     "sporty,fresh,energetic,masculine"),
    ("Chanel Bleu de Chanel",      "Chanel", "aromatic_woody",
     "lemon,mint,pink_pepper,grapefruit", "ginger,nutmeg,jasmine,iso_e_super", "sandalwood,patchouli,vetiver,cedar",
     "modern,masculine,refined,French"),
    ("Chanel Egoiste",             "Chanel", "woody_aromatic",
     "rosewood,coriander,bergamot", "rose,jasmine,carnation,geranium", "sandalwood,vetiver,amber,civet",
     "masculine,bold,controversial,iconic,classic"),
    ("Chanel Pour Monsieur",       "Chanel", "aromatic_fougere",
     "lemon,neroli,bergamot", "cardamom,nutmeg,geranium", "oakmoss,vetiver,sandalwood,amber",
     "classic,gentleman,refined,timeless"),
    ("Chanel Sycomore",            "Chanel", "woody_aromatic",
     "grapefruit,juniper,nutmeg,pepper,bergamot", "vetiver,cypress", "sandalwood,cedar,white_musk,vetiver",
     "austere,smoky,woody,exclusive"),
    ("Chanel Jersey",              "Chanel", "floral_musky",
     "lavender,bergamot,neroli", "rose,jasmine,iris", "white_musk,vanilla,sandalwood",
     "soft,powdery,delicate,exclusive"),
    # ── DIOR ────────────────────────────────────────────────────────────────
    ("Dior Sauvage",               "Dior", "fresh_spicy",
     "bergamot,pink_pepper", "geranium,lavender,saffron", "ambroxan,cedar,vetiver",
     "bold,masculine,wild,magnetic,bestseller"),
    ("Dior Sauvage Elixir",        "Dior", "spicy_woody",
     "grapefruit,cardamom,nutmeg", "lavender,sandalwood", "hawthorn,amber,licorice,vanilla",
     "intense,dark,warm,powerful,masculine"),
    ("Dior Sauvage Parfum",        "Dior", "woody_spicy",
     "bergamot", "sandalwood,lavender", "frankincense,ambroxan,cedar",
     "raw,powerful,masculine,dark,bold"),
    ("Dior Miss Dior",             "Dior", "floral_chypre",
     "bergamot,pink_pepper,blood_orange", "rose,peony,lily_of_the_valley", "sandalwood,white_musk,patchouli",
     "fresh,romantic,feminine,spring,classic"),
    ("Dior Miss Dior Blooming Bouquet","Dior","floral",
     "mandarin,peony,pink_pepper", "peony,rose", "white_musk,sandalwood",
     "light,feminine,delicate,floral,spring"),
    ("Dior Poison",                "Dior", "oriental_floral",
     "plum,wild_berries,cinnamon", "tuberose,rose,jasmine,carnation,lily", "sandalwood,amber,vetiver,oakmoss,civet",
     "dark,seductive,daring,iconic,bold"),
    ("Dior Hypnotic Poison",       "Dior", "oriental_gourmand",
     "coconut,apricot,plum,bergamot,bitter_almond", "jasmine,rose,cinnamon,rosewood", "vanilla,musk,sandalwood,cedar",
     "sensual,addictive,sweet,dark,nocturnal"),
    ("Dior Fahrenheit",            "Dior", "woody_floral_musk",
     "lavender,mandarin,hawthorn,bergamot", "violet,lily_of_the_valley,geranium", "leather,vetiver,sandalwood,amber",
     "daring,unconventional,masculine,iconic"),
    ("Dior Homme",                 "Dior", "aromatic_fougere",
     "iris,lavender,bergamot", "iris,ambrette,vetiver", "amber,vetiver,leather",
     "iris,sophisticated,masculine,elegant"),
    ("Dior Homme Intense",         "Dior", "oriental_woody",
     "lavender", "iris,ambrette", "vetiver,cedar,amber",
     "masculine,iris,elegant,intense,seductive"),
    ("Dior Homme Sport",           "Dior", "aromatic_fougere",
     "bergamot,blood_orange,pink_pepper", "geranium,elemi,cardamom", "vetiver,cedar,iso_e_super",
     "sporty,fresh,masculine,energetic"),
    ("Dior J adore",               "Dior", "floral",
     "champagne_accord,mandarin,orchid,magnolia", "jasmine,lily_of_the_valley,rose", "musk,sandalwood,cedar,patchouli",
     "luminous,feminine,floral,celebratory,elegant"),
    ("Dior J adore Absolu",        "Dior", "oriental_floral",
     "mandarin,bergamot", "rose,jasmine,ylang_ylang,tuberose", "amber,musk,civet,sandalwood",
     "opulent,rich,feminine,golden,sensual"),
    ("Dior Addict",                "Dior", "floral_oriental",
     "mandarin,bergamot,orange_blossom", "rose,jasmine,madagascar_vanilla", "sandalwood,vanilla,tonka_bean,musk",
     "addictive,feminine,warm,opulent,sweet"),
    ("Dior Dolce Vita",            "Dior", "floral_fruity",
     "peach,lemon,magnolia", "rose,ylang_ylang,carnation,heliotrope,cedar", "sandalwood,vanilla,musk,amber",
     "italian,sweet,feminine,sunny,joyful"),
    ("Dior Escale a Portofino",    "Dior", "citrus",
     "lemon,bergamot,mandarin,grapefruit,lime,yuzu,petitgrain,orange", "rose", "cedar",
     "italian,fresh,citrus,summer,light"),
    # ── GUERLAIN ────────────────────────────────────────────────────────────
    ("Guerlain Shalimar",          "Guerlain", "oriental",
     "bergamot,lemon", "rose,iris,jasmine", "vanilla,amber,leather,frankincense,civet,opoponax",
     "vintage,sensual,opulent,exotic,iconic"),
    ("Guerlain Mitsouko",          "Guerlain", "floral_chypre",
     "bergamot,lemon,mandarin", "rose,jasmine,ylang_ylang,lily_of_the_valley,iris", "oakmoss,vetiver,sandalwood,musk,civet",
     "legendary,mysterious,complex,timeless"),
    ("Guerlain L Heure Bleue",     "Guerlain", "floral_oriental",
     "bergamot,lemon,coriander,anise", "rose,violet,iris,heliotrope,carnation", "sandalwood,benzoin,musk,vanilla",
     "nostalgic,dreamy,twilight,feminine,complex"),
    ("Guerlain Vol de Nuit",       "Guerlain", "oriental_fougere",
     "galbanum,bergamot,mandarin,lemon", "rose,jasmine,orchid,iris,vetiver", "sandalwood,vanilla,amber,civet,leather",
     "aviation,freedom,mysterious,vintage"),
    ("Guerlain Mon Guerlain",      "Guerlain", "oriental_floral",
     "bergamot,grapefruit", "lavender,jasmine,peony", "vanilla,sandalwood,white_musk,coumarin",
     "French,romantic,soft,feminine,warm"),
    ("Guerlain Idylle",            "Guerlain", "floral",
     "blackcurrant,bergamot,lemon,pink_pepper", "rose,lily_of_the_valley,jasmine,peony", "sandalwood,musk,vanilla,iris",
     "romantic,floral,feminine,fresh,elegant"),
    ("Guerlain Aqua Allegoria Pera Granita","Guerlain","citrus_fruity",
     "pear,yuzu,bergamot", "peony,rose", "white_musk,cedar",
     "fresh,summery,fruity,light,cheerful"),
    ("Guerlain Vetiver",           "Guerlain", "woody_aromatic",
     "lemon,bergamot,petitgrain", "tobacco,nutmeg,geranium", "vetiver,sandalwood,oakmoss",
     "classic,masculine,earthy,green,chypre"),
    ("Guerlain La Petite Robe Noire","Guerlain","fruity_floral",
     "black_currant,raspberry,cherry,red_berries", "rose,licorice", "patchouli,iris,vanilla,musk",
     "fashion,dark_fruit,feminine,modern,iconic"),
    # ── HERMES ──────────────────────────────────────────────────────────────
    ("Hermes Terre d Hermes",      "Hermes", "woody_aromatic",
     "orange,grapefruit", "pepper,geranium,flint", "vetiver,cedar,benzoin",
     "earthy,mineral,masculine,grounded"),
    ("Hermes Eau des Merveilles",  "Hermes", "woody_amber",
     "orange,pink_pepper,lemon", "iris,cedar,incense", "amber,vetiver,oak,lichen",
     "mysterious,amber,mineral,elegant,feminine"),
    ("Hermes Un Jardin sur le Nil","Hermes","green_floral",
     "grapefruit,lotus,green_mango", "peony,rose,lotus_flower", "wood,incense",
     "nile,Egypt,green,fresh,exotic"),
    ("Hermes Un Jardin en Mediterranee","Hermes","aromatic_aquatic",
     "lemon,cypress,mastic_tree", "cedar,fig_leaf,jasmine", "sandalwood,patchouli,cedar",
     "mediterranean,fig,sunny,fresh,greek"),
    ("Hermes Un Jardin sur la Mousson","Hermes","green",
     "coriander,ginger,cardamom", "vetiver,magnolia,grass", "white_musk",
     "India,monsoon,green,wet,contemplative"),
    ("Hermes Kelly Caleche",       "Hermes", "floral_chypre",
     "bergamot,lemon,neroli", "rose,iris,jasmine,ylang_ylang", "vetiver,oakmoss,sandalwood,civet",
     "equestrian,feminine,chic,classic,french"),
    ("Hermes 24 Faubourg",         "Hermes", "white_floral",
     "orange,hyacinth,peach", "tuberose,iris,jasmine", "sandalwood,amber,musk",
     "white,feminine,Parisian,elegant"),
    ("Hermes Voyage d Hermes",     "Hermes", "aromatic_woody",
     "grapefruit,geranium,pepper,cardamom", "iris,musk,cedarwood", "frankincense,amber,sandalwood",
     "minimalist,freedom,masculine,modern"),
    # ── TOM FORD ────────────────────────────────────────────────────────────
    ("Tom Ford Black Orchid",      "Tom Ford", "floral_oriental",
     "bergamot,mandarin,black_pepper", "ylang_ylang,jasmine,tuberose", "patchouli,vetiver,sandalwood,vanilla",
     "dark,sensual,mysterious,luxurious"),
    ("Tom Ford Oud Wood",          "Tom Ford", "woody_oriental",
     "cardamom,chinese_pepper", "oud,sandalwood,rosewood,vetiver", "amber,tonka_bean",
     "opulent,dark,masculine,luxurious,oud"),
    ("Tom Ford Tobacco Vanille",   "Tom Ford", "oriental_spicy",
     "tobacco_leaf,spices", "tobacco_blossom,jasmine,ginger,spices", "vanilla,cocoa,dried_fruit,wood",
     "warm,sweet,dark,masculine,cozy"),
    ("Tom Ford Neroli Portofino",  "Tom Ford", "citrus_aromatic",
     "bergamot,lemon,orange,mandarin,blood_orange,neroli", "neroli,rosemary,lavender,pink_pepper", "amber,oakmoss,white_musk,angelica_root",
     "italian,citrus,fresh,mediterranean,sunny"),
    ("Tom Ford Tuscan Leather",    "Tom Ford", "leather",
     "raspberry,saffron", "jasmine,rose,thyme", "leather,amber,white_musk,suede",
     "leather,bold,raw,powerful,Tuscan"),
    ("Tom Ford Rose Prick",        "Tom Ford", "floral_spicy",
     "pink_pepper,elemi", "rose_de_mai,damask_rose,rose,iris", "oud,amber,musk,sandalwood,suede",
     "thorny,rose,daring,modern,luxury"),
    ("Tom Ford Grey Vetiver",      "Tom Ford", "woody_aromatic",
     "grapefruit,mandarin,orange,petitgrain", "orris,sage,geranium,oakmoss", "vetiver,sandalwood,amber,tonka_bean",
     "grey,mineral,sophisticated,masculine"),
    ("Tom Ford Velvet Orchid",     "Tom Ford", "oriental_floral",
     "rum,black_pepper", "orchid,jasmine,rose", "labdanum,sandalwood,musk,heliotrope,vanilla",
     "velvet,orchid,opulent,feminine,nocturnal"),
    ("Tom Ford Fleur de Portofino","Tom Ford","floral",
     "bergamot,neroli,mandarin", "jasmine,rose,iris,orange_blossom", "sandalwood,musk,ambergris",
     "italian,white_floral,sunny,feminine,airy"),
    ("Tom Ford Lost Cherry",       "Tom Ford", "oriental_gourmand",
     "cherry,black_cherry,sour_cherry", "turkish_rose,jasmine,almond", "benzoin,tonka_bean,sandalwood,madagascar_vanilla",
     "cherry,sweet,dark,feminine,indulgent"),
    ("Tom Ford Soleil Blanc",      "Tom Ford", "floral_musky",
     "bergamot,ginger,cardamom", "ylang_ylang,jasmine,peony,magnolia", "sandalwood,musk,amber,heliotrope",
     "summer,sun,white,beach,sensual"),
    ("Tom Ford Santal Blush",      "Tom Ford", "woody_floral",
     "saffron,ginger,pink_pepper", "rose,jasmine,ylang_ylang", "sandalwood,vanilla,amber",
     "sandalwood,blushing,warm,romantic"),
    ("Tom Ford Ombre Leather",     "Tom Ford", "leather_floral",
     "cardamom,pink_pepper,violet", "rose,jasmine,patchouli", "leather,vetiver,oakmoss,white_musk",
     "leather,dark,modern,edgy,unisex"),
    ("Tom Ford Cafe Rose",         "Tom Ford", "floral_oriental",
     "pink_pepper,saffron", "rose,turkish_rose,carnation,coffee", "oud,sandalwood,patchouli,amber",
     "coffee,rose,Turkish,oriental,opulent"),
    # ── MAISON MARGIELA ─────────────────────────────────────────────────────
    ("Maison Margiela Beach Walk", "Maison Margiela", "fresh_aquatic",
     "bergamot,lemon,pink_pepper", "ylang_ylang,iris", "coconut,cedar,white_musk,ambroxan",
     "summery,carefree,warm,nostalgic,beach"),
    ("Maison Margiela By the Fireplace","Maison Margiela","warm_spicy",
     "pink_pepper,orange,clove", "chestnut,guaiac_wood,jasmine", "vanilla,cashmeran,white_musk",
     "fireplace,cozy,winter,warm,sweet"),
    ("Maison Margiela Flower Market","Maison Margiela","floral_woody",
     "bergamot,pink_pepper,lemon", "rose,peony,freesia,jasmine", "sandalwood,cedar,white_musk",
     "flower_market,fresh,spring,bright,feminine"),
    ("Maison Margiela Jazz Club",  "Maison Margiela","oriental_woody",
     "rum,blood_orange,pink_pepper", "clary_sage,tobacco,vetiver", "tonka_bean,vanilla,musk",
     "jazz,nocturnal,smoky,masculine,cool"),
    ("Maison Margiela Lazy Sunday Morning","Maison Margiela","floral_musky",
     "bergamot,rose", "rose,peony,jasmine", "white_musk,sandalwood,iris",
     "soft,cozy,morning,clean,lazy"),
    ("Maison Margiela Springtime in a Park","Maison Margiela","green_floral",
     "violet_leaf,bergamot,green", "rose,violet,jasmine", "white_musk,sandalwood",
     "park,spring,green,fresh,bright"),
    ("Maison Margiela Under the Lemon Trees","Maison Margiela","citrus",
     "lemon,bergamot,yuzu", "magnolia,neroli", "white_musk,cedar",
     "italian,citrus,summer,fresh,amalfi"),
    ("Maison Margiela At the Barber's","Maison Margiela","fougere",
     "bergamot,pink_pepper,vetiver", "iris,geranium,clary_sage", "tonka_bean,white_musk,sandalwood",
     "barbershop,clean,masculine,fresh,groomed"),
    # ── BYREDO ──────────────────────────────────────────────────────────────
    ("Byredo Gypsy Water",         "Byredo", "fresh_woody",
     "bergamot,lemon,pepper", "juniper,orris,pine_needles", "sandalwood,vanilla,amber",
     "nomadic,bohemian,clean,spiritual"),
    ("Byredo Bal d Afrique",       "Byredo", "floral_woody",
     "lemon,bergamot,african_violet", "marigold,neroli,jasmine", "vetiver,musk,cedarwood,amber",
     "african,nomadic,warm,exotic"),
    ("Byredo Blanche",             "Byredo", "floral_musky",
     "pink_pepper,white_rose", "peony,rose", "sandalwood,white_musk",
     "white,clean,pure,modern,Swedish"),
    ("Byredo Biblioteque",         "Byredo", "woody_aromatic",
     "pink_pepper,peach", "violet,peach_wood,peony", "vanilla,leather,sandalwood,white_musk",
     "library,books,cozy,intellectual,warm"),
    ("Byredo Mojave Ghost",        "Byredo", "floral_woody",
     "sapodilla,magnolia", "violet,sandalwood,ambrette", "cedar,musk,sandalwood",
     "desert,minimal,clean,American,sunny"),
    ("Byredo Oud Immortel",        "Byredo", "woody_oriental",
     "pink_pepper,frankincense", "oud,papyrus,sandalwood", "black_musk,amber,vetiver",
     "oud,dark,immortal,powerful,incense"),
    ("Byredo Accord Oud",          "Byredo", "oriental_woody",
     "saffron,cedarwood", "oud,patchouli,sandalwood", "amber,musk",
     "oud,arabic,dark,incense,powerful"),
    ("Byredo Pulp",                "Byredo", "fruity",
     "pomegranate,black_currant,fig,pear,plum", "peach,jasmine,rose", "sandalwood,cedar,musk",
     "fruity,summer,fresh,juicy,playful"),
    ("Byredo Sundazed",            "Byredo", "woody_floral",
     "pink_pepper,mandarin", "cyclamen,hyacinth,peach", "sandalwood,musk,ambroxan",
     "summery,optimistic,hazy,warm"),
    ("Byredo Super Cedar",         "Byredo", "woody",
     "rose,pink_pepper", "cedar,rose", "cedar,musk,ambroxan",
     "cedar,woody,fresh,unisex,clean"),
    # ── LE LABO ─────────────────────────────────────────────────────────────
    ("Le Labo Santal 33",          "Le Labo", "woody_spicy",
     "cardamom,iris,violet,ambrette", "papyrus,sandalwood,cedarwood,leather", "sandalwood,musk,amber",
     "cult,cozy,unisex,sandalwood,American"),
    ("Le Labo Rose 31",            "Le Labo", "floral_woody",
     "rose,lemon,bergamot,grapefruit", "cumin,guaiac_wood,geranium,cedar", "sandalwood,amber,musk",
     "rose,masculine,modern,complex"),
    ("Le Labo Another 13",         "Le Labo", "musky",
     "ambrette", "ambrette,jasmine", "musk,ambroxan",
     "skin,minimal,warm,sensual,cult"),
    ("Le Labo Bergamote 22",       "Le Labo", "citrus_aromatic",
     "bergamot,grapefruit,pink_pepper,neroli", "cedar,musk,violet", "amber,musk,galbanum",
     "citrus,NY,fresh,clean,unisex"),
    ("Le Labo Jasmin 17",          "Le Labo", "floral",
     "bergamot,lemon", "jasmine,neroli", "musk,amber,sandalwood",
     "jasmine,solar,feminine,natural"),
    ("Le Labo Vetiver 46",         "Le Labo", "woody_aromatic",
     "citrus,bergamot", "geranium,elemi", "vetiver,cedar,sandalwood,oakmoss",
     "smoky,earthy,green,LA,unisex"),
    ("Le Labo Labdanum 18",        "Le Labo", "oriental",
     "spices,tobacco", "labdanum,incense", "labdanum,sandalwood,musk",
     "resinous,dark,smoky,powerful"),
    ("Le Labo Baie 19",            "Le Labo", "green_aromatic",
     "bay_leaf,bergamot", "bay_leaf,ginger,jasmine", "sandalwood,musk,amber",
     "mediterranean,herbal,green,fresh"),
    ("Le Labo Oud 27",             "Le Labo", "oriental_woody",
     "oud,black_pepper", "oud,patchouli,labdanum", "amber,sandalwood,musk",
     "oud,dark,rich,meditative,incense"),
    # ── JO MALONE ───────────────────────────────────────────────────────────
    ("Jo Malone Peony Blush Suede","Jo Malone","floral",
     "mandarin,orange", "rose,peony,jasmine", "suede,vanilla,white_musk",
     "soft,romantic,feminine,delicate"),
    ("Jo Malone Lime Basil Mandarin","Jo Malone","citrus_aromatic",
     "lime,mandarin", "basil,lilac,white_thyme", "amber,patchouli",
     "fresh,british,signature,lime,herbal"),
    ("Jo Malone Wood Sage Sea Salt","Jo Malone","aromatic_aquatic",
     "ambrette,sea_salt", "sage", "driftwood,ambrette",
     "ocean,salt,earthy,fresh,coastal"),
    ("Jo Malone English Pear Freesia","Jo Malone","fruity_floral",
     "pear,melon", "freesia,rose,white_musk", "white_musk,patchouli,amber,rhubarb",
     "english,pear,fresh,autumn,feminine"),
    ("Jo Malone Pomegranate Noir", "Jo Malone", "fruity_floral",
     "pomegranate,raspberry,plum", "rose,pink_pepper,guaiac_wood", "musk,patchouli,spicy_woods",
     "dark,fruity,noir,dramatic,festive"),
    ("Jo Malone Oud Velvet Mood",  "Jo Malone", "oriental_woody",
     "cardamom,cinnamon", "oud,praline", "sandalwood,amber,musk",
     "oud,warm,festive,luxurious,british"),
    ("Jo Malone Myrrh Tonka",      "Jo Malone", "oriental",
     "almond,ginger", "tonka_bean,heliotrope", "myrrh,benzoin",
     "comforting,warm,sweet,spicy,Christmas"),
    ("Jo Malone Amber Lavender",   "Jo Malone", "oriental_aromatic",
     "lavender,eucalyptus,mint", "amber,patchouli", "vetiver,amber,sandalwood",
     "amber,lavender,warm,aromatic"),
    ("Jo Malone Nectarine Blossom Honey","Jo Malone","fruity_floral",
     "nectarine,cassis", "peach,magnolia,white_rose", "honey,vetiver,apricot",
     "sunny,honey,feminine,fresh,fruity"),
    # ── CREED ───────────────────────────────────────────────────────────────
    ("Creed Aventus",              "Creed", "fruity_chypre",
     "bergamot,lemon,mandarin,grapefruit", "rose,jasmine,birch,cardamom", "oakmoss,ambergris,vanilla,sandalwood",
     "confident,powerful,successful,refined"),
    ("Creed Silver Mountain Water","Creed", "green_aquatic",
     "bergamot,mandarin,green_tea,black_currant", "neroli,ginger", "sandalwood,musk,ambergris",
     "alpine,fresh,crisp,masculine"),
    ("Creed Green Irish Tweed",    "Creed", "aromatic_fougere",
     "lemon,verbena", "orris,sandalwood,violet_leaf", "ambergris,sandalwood",
     "green,fresh,Irish,polo,masculine"),
    ("Creed Millesime Imperial",   "Creed", "citrus_aquatic",
     "bergamot,mandarin,black_currant", "sea_notes,musk,iris", "ambergris,sandalwood,white_musk",
     "ocean,royal,fresh,imperial,crisp"),
    ("Creed Original Vetiver",     "Creed", "woody_aromatic",
     "bergamot,grapefruit,mandarin,lemon", "geranium,cardamom,vetiver,ginger", "ambergris,musk,vetiver",
     "clean,earthy,elegant,masculine"),
    ("Creed Himalaya",             "Creed", "woody_aromatic",
     "bergamot,lemon,orange", "geranium,jasmine,iso_e_super,sandalwood", "ambergris,musk,sandalwood",
     "mountain,clean,fresh,masculine,crisp"),
    ("Creed Viking",               "Creed", "aromatic_woody",
     "bergamot,pink_pepper,grapefruit", "lavender,rose,geranium,elemi", "vetiver,sandalwood,oakmoss,ambergris",
     "norse,powerful,fresh,masculine"),
    ("Creed Love in White",        "Creed", "floral_musky",
     "mandarin,bergamot,rice", "iris,magnolia,rose,white_musk", "sandalwood,ambergris,musk,vanilla",
     "white,pure,feminine,clean,romantic"),
    ("Creed Floralie",             "Creed", "floral",
     "blackcurrant,bergamot,pink_pepper", "rose,jasmine,peony", "sandalwood,musk,amber",
     "feminine,floral,garden,elegant"),
    # ── AMOUAGE ─────────────────────────────────────────────────────────────
    ("Amouage Interlude Man",      "Amouage", "oriental_woody",
     "oregano,bergamot,clary_sage,pink_pepper", "patchouli,sandalwood,oud,cistus", "frankincense,amber,leather",
     "complex,oud,masculine,arabic,meditative"),
    ("Amouage Gold Man",           "Amouage", "floral_oriental",
     "bergamot,lemon,petitgrain,frankincense", "jasmine,rose,lily_of_the_valley", "sandalwood,vetiver,oakmoss,civet,amber",
     "opulent,gold,arabic,masterpiece,floral"),
    ("Amouage Reflection Man",     "Amouage", "aromatic_floral",
     "bergamot,rosemary,petitgrain", "geranium,iris,jasmine,neroli,rose,ylang_ylang", "sandalwood,musk,vetiver",
     "clean,reflective,classical,masculine,bright"),
    ("Amouage Epic Woman",         "Amouage", "oriental_spicy",
     "black_pepper,cardamom,clary_sage,myrrh", "orris,jasmine,coriander,rose,sandalwood", "sandalwood,labdanum,olibanum,frankincense",
     "epic,powerful,oriental,luxurious,complex"),
    ("Amouage Beloved Man",        "Amouage", "aromatic_oriental",
     "davana,neroli,bergamot", "jasmine,rose,mate,agarwood", "sandalwood,amber,musk",
     "beloved,warm,oriental,romantic"),
    ("Amouage Fate Man",           "Amouage", "oriental_woody",
     "black_pepper,nutmeg,cardamom,oud", "tobacco,cistus,oud", "labdanum,vetiver,leather",
     "fate,dark,smoky,oud,serious"),
    ("Amouage Honour Man",         "Amouage", "aromatic_woody",
     "petitgrain,pepper,bergamot,aldehydes", "iris,mate,birch,vetiver", "oakmoss,cedar,leather,vetiver",
     "honour,masculine,distinguished,fresh"),
    ("Amouage Library Opus VII",   "Amouage", "oriental",
     "pink_pepper,bergamot", "cistus,amber,labdanum", "musk,amber,labdanum,oud",
     "bibliophile,serious,dark,complex"),
    # ── MFK ─────────────────────────────────────────────────────────────────
    ("MFK Baccarat Rouge 540",     "MFK", "floral_woody",
     "saffron,jasmine", "ambroxan,cedar,fir_resin", "white_musk,ambergris",
     "luminous,amber,woody,seductive,cult"),
    ("MFK Baccarat Rouge 540 Extrait","MFK","floral_woody",
     "saffron,jasmine", "ambroxan,cedar", "white_musk,ambergris",
     "intense,deep,concentrated,cult,luxury"),
    ("MFK Grand Soir",             "MFK", "oriental",
     "bergamot,cardamom,saffron", "amber,benzyl_benzoate", "vanilla,amber,musk",
     "grand,evening,opulent,warm,amber"),
    ("MFK Aqua Universalis",       "MFK", "citrus_musky",
     "bergamot,lemon,grapefruit", "lily_of_the_valley,rose,jasmine", "musk,cedar,sandalwood",
     "clean,universal,fresh,white,accessible"),
    ("MFK Oud Satin Mood",         "MFK", "oriental_floral",
     "pink_pepper,davana", "rose,oud,jasmine", "vanilla,benzoin,musk",
     "oud,velvety,sensual,pink,luxurious"),
    ("MFK Gentle Fluidity Gold",   "MFK", "oriental_woody",
     "nutmeg,coriander,juniper", "musk,vanilla,amber", "oud,sandalwood,amber",
     "fluidity,warm,golden,unisex,cozy"),
    ("MFK Amyris Femme Extrait",   "MFK", "floral_woody",
     "neroli,bergamot", "rose,iris", "sandalwood,amyris,musk",
     "pure,feminine,floral,luminous"),
    # ── FREDERIC MALLE ──────────────────────────────────────────────────────
    ("Frederic Malle Portrait of a Lady","FM","oriental_floral",
     "rose,blackcurrant", "rose,turkish_rose,raspberry,jasmine", "patchouli,musk,sandalwood,frankincense",
     "grand,opulent,romantic,artistic,masterpiece"),
    ("Frederic Malle Carnal Flower","FM","floral",
     "eucalyptus,melon,ylang_ylang", "tuberose,jasmine", "coconut,white_musk,beeswax",
     "tuberose,sensual,white,carnal"),
    ("Frederic Malle Musc Ravageur","FM","oriental",
     "bergamot,mandarin,lavender", "cinnamon,cloves,ginger", "vanilla,musk,amber,sandalwood",
     "ravishing,sensual,dark,musky,iconic"),
    ("Frederic Malle En Passant",  "FM", "floral_musky",
     "cucumber,wheat", "white_lilac,iris", "white_musk,cedar",
     "spring,impressionist,lilac,watery,dreamy"),
    ("Frederic Malle Cologne Indelebile","FM","floral_musky",
     "neroli,aldehydes,cardamom", "jasmine,rose,ylang_ylang", "white_musk,iris",
     "orange_blossom,white,luminous,clean"),
    ("Frederic Malle Synthetic Jungle","FM","green_woody",
     "basil,petitgrain,pink_pepper", "clary_sage,jasmine,hedione", "vetiver,cedarwood,sandalwood",
     "jungle,green,modern,synthetic,natural"),
    # ── SERGE LUTENS ────────────────────────────────────────────────────────
    ("Serge Lutens Feminite du Bois","Serge Lutens","woody_floral",
     "orange,plum,bergamot", "rose,jasmine,ylang_ylang,violet", "sandalwood,cedar,cinnamon,vanilla",
     "feminine,woody,original,unexpected,pioneering"),
    ("Serge Lutens Ambre Sultan",  "Serge Lutens","oriental",
     "oregano,bay_leaf,coriander,myrtle", "cistus,angelica,amber", "sandalwood,patchouli,amber,resins",
     "amber,warm,resinous,Moroccan,powerful"),
    ("Serge Lutens Five O Clock au Gingembre","Serge Lutens","aromatic_spicy",
     "ginger,petitgrain", "ginger,black_pepper,tea", "sandalwood,white_musk",
     "tea_time,ginger,warm,witty,english"),
    ("Serge Lutens Arabie",        "Serge Lutens","oriental_spicy",
     "cardamom,dry_dates,mandarin", "cumin,coriander,frankincense,caraway", "sandalwood,amber,cedar,vanilla",
     "arabic,dates,dry,oriental,mysterious"),
    ("Serge Lutens Santal Majuscule","Serge Lutens","woody_oriental",
     "cocoa,rose", "sandalwood,cocoa,rose", "sandalwood,cedar,amber",
     "sandalwood,gourmand,French,elegant"),
    ("Serge Lutens Un Bois Vanille","Serge Lutens","oriental",
     "iris,orange", "vanilla,benzoin,iris", "vanilla,benzoin,amber",
     "vanilla,Tahitian,warm,comforting,feminine"),
    ("Serge Lutens Jeux de Peau",  "Serge Lutens","gourmand",
     "bread,wheat,butter,milk", "almond,sandalwood,honey", "vanilla,amber,musk",
     "bread,buttery,warm,milky,comforting"),
    # ── DIPTYQUE ────────────────────────────────────────────────────────────
    ("Diptyque Philosykos",        "Diptyque", "woody",
     "fig_leaf,green", "fig_wood,fig_leaf", "cedar,white_musk",
     "natural,earthy,summery,unique,fig"),
    ("Diptyque Eau des Sens",      "Diptyque", "floral_oriental",
     "bigarade,juniper", "angelica,jasmine", "patchouli,amber,musk",
     "complex,wild,sensual,unique"),
    ("Diptyque Eau Rose",          "Diptyque", "floral",
     "green_rose,pea_flower,pink_pepper", "rose,lychee", "musk,white_musk",
     "rose,fresh,feminine,youthful,light"),
    ("Diptyque Tam Dao",           "Diptyque", "woody",
     "juniper,sandalwood,cypress", "sandalwood,cedarwood,rosewood", "white_musk,amber",
     "sandalwood,meditative,clean,woody,calming"),
    ("Diptyque Do Son",            "Diptyque", "floral",
     "white_flowers,water_lily", "tuberose,orange_blossom,rose", "white_musk,cedarwood",
     "vietnam,white,luminous,feminine"),
    ("Diptyque Vetyverio",         "Diptyque", "woody_aromatic",
     "grapefruit,vetiver", "geranium,vetiver", "vetiver,cedar,white_musk",
     "vetiver,green,smoky,masculine,earth"),
    ("Diptyque L Ombre dans l Eau","Diptyque","floral_green",
     "blackcurrant,blackcurrant_leaves", "rose", "musk,cedarwood",
     "garden,fresh,blackcurrant,feminine"),
    ("Diptyque Eau Duelle",        "Diptyque", "oriental",
     "bergamot,blackcurrant,pink_pepper", "vanilla,iris,cedarwood", "vanilla,tonka_bean,white_musk",
     "vanilla,oriental,warm,quiet,comforting"),
    ("Diptyque Olene",             "Diptyque", "floral",
     "bergamot,pink_pepper", "narcissus,jasmine,honeysuckle,mimosa,ylang_ylang", "musk,white_musk,sandalwood",
     "floral,garden,spring,Paris,feminine"),
    # ── PENHALIGONS ─────────────────────────────────────────────────────────
    ("Penhaligons Halfeti",        "Penhaligons","oriental_woody",
     "bergamot,rose,blackcurrant", "jasmine,turkish_rose,oud", "leather,amber,sandalwood,vanilla",
     "opulent,dark,romantic,british"),
    ("Penhaligons Halfeti Leather","Penhaligons","oriental_leather",
     "bergamot,black_pepper,saffron", "rose,leather,oud", "amber,vanilla,sandalwood",
     "british,dark,opulent,leather"),
    ("Penhaligons Blenheim Bouquet","Penhaligons","citrus_aromatic",
     "lemon,lime,bergamot,black_pepper", "nutmeg,geranium", "pine,oakmoss,musk",
     "edwardian,british,crisp,classic,masculine"),
    ("Penhaligons Empressa",       "Penhaligons","floral_woody",
     "bergamot,pink_pepper,yuzu", "rose,peony,magnolia", "iris,sandalwood,musk",
     "british,regal,feminine,elegant,floral"),
    ("Penhaligons Clandestine Clara","Penhaligons","oriental_floral",
     "lemon,bergamot,grapefruit,rose", "rose,heliotrope,vetiver,jasmine", "vanilla,musk,cedar,sandalwood",
     "british,romantic,mysterious,floral"),
    ("Penhaligons Opus 1870",      "Penhaligons","aromatic",
     "lavender,rosemary,petitgrain", "geranium,galbanum,vetiver", "oakmoss,cedarwood,sandalwood",
     "victorian,british,classic,fougere,masculine"),
    # ── YSL ─────────────────────────────────────────────────────────────────
    ("YSL Black Opium",            "YSL", "oriental_gourmand",
     "pink_pepper,orange", "coffee,jasmine", "vanilla,cedar,white_musk,caramel",
     "addictive,seductive,bold,night,rock"),
    ("YSL Libre",                  "YSL", "floral_aromatic",
     "mandarin", "lavender,orange_blossom,jasmine", "musk,vanilla,cedar",
     "free,feminine,modern,bold,French"),
    ("YSL Mon Paris",              "YSL", "floral_fruity",
     "pear,strawberry,white_flowers", "jasmine,peony,rose", "white_musk,patchouli,ambroxan",
     "Paris,love,romantic,feminine,sweet"),
    ("YSL Opium",                  "YSL", "oriental",
     "plum,clementine,aldehydes", "rose,jasmine,lily_of_the_valley,cloves,cinnamon", "sandalwood,vetiver,cedarwood,amber,labdanum",
     "iconic,bold,oriental,controversial,powerful"),
    ("YSL Kouros",                 "YSL", "aromatic_fougere",
     "aldehydes,bergamot,lemon,coriander", "jasmine,rose,geranium,ylang_ylang,carnation,cinnamon", "oakmoss,amber,vetiver,civet,frankincense",
     "classic,masculine,iconic,greek,bold"),
    ("YSL L Homme",                "YSL", "woody_aromatic",
     "bergamot,lemon,ginger", "basil,violet,white_cedar", "tonka_bean,white_cedar,vetiver",
     "masculine,French,modern,elegant"),
    ("YSL La Nuit de l Homme",     "YSL", "oriental_woody",
     "bergamot,cardamom", "cedar,lavender", "vetiver,amber,tonka_bean",
     "seductive,nocturnal,masculine,intimate"),
    ("YSL Nu",                     "YSL", "floral_woody",
     "bergamot,magnolia", "iris,white_flowers", "sandalwood,musk,amber",
     "nude,minimalist,sensual,modern"),
    # ── GIORGIO ARMANI ──────────────────────────────────────────────────────
    ("Armani Acqua di Gio",        "Armani", "fresh_aquatic",
     "lemon,lime,bergamot,marine", "jasmine,rose,geranium,calone", "cedar,sandalwood,white_musk",
     "fresh,clean,ocean,masculine,iconic"),
    ("Armani Acqua di Gio Profumo","Armani","aromatic_woody",
     "bergamot,marine", "geranium,rosemary", "patchouli,incense,amber,musk",
     "intense,aquatic,deep,masculine"),
    ("Armani Si",                  "Armani", "floral_fruity",
     "blackcurrant,bergamot,mandarin", "rose,freesia", "vanilla,ambroxan,white_musk",
     "modern,feminine,powerful,rose,yes"),
    ("Armani Si Passione",         "Armani", "floral_fruity",
     "blackcurrant,bergamot", "rose,freesia,neroli", "vanilla,musk,patchouli",
     "passionate,feminine,warm,floral"),
    ("Armani Code",                "Armani", "oriental_fougere",
     "bergamot,lemon", "star_anise,neroli,jasmine,orange_blossom", "labdanum,musk,guaiac_wood,olive_blossom",
     "seductive,masculine,code,iconic,dark"),
    ("Armani Prive Rose d Arabie",  "Armani","floral_oriental",
     "bergamot,pepper", "rose,jasmine,patchouli", "amber,vanilla,sandalwood",
     "arabic,rose,opulent,exclusive"),
    ("Armani Prive Pivoine Suzhou","Armani","floral_musky",
     "pink_pepper,mandarin", "peony,rose,jasmine", "white_musk,sandalwood,cedar",
     "Chinese,peony,spring,delicate,exclusive"),
    # ── VERSACE ─────────────────────────────────────────────────────────────
    ("Versace Eros",               "Versace","oriental_fougere",
     "lemon,apple,mint", "geranium,ambrette,clary_sage", "vanilla,vetiver,oakmoss,tonka_bean",
     "passionate,masculine,greek,powerful"),
    ("Versace Bright Crystal",     "Versace","floral_fruity",
     "pomegranate,yuzu,frost", "peony,magnolia,lotus", "musk,amber,mahogany",
     "crystal,feminine,spring,bright,fresh"),
    ("Versace Dylan Blue",         "Versace","fresh_woody",
     "grapefruit,bergamot,violet_leaf,water_lily", "patchouli,violet,jasmine,papyrus", "incense,amber,musk,leather",
     "blue,fresh,modern,masculine,greek"),
    ("Versace The Dreamer",        "Versace","aromatic",
     "tarragon,flax,bergamot,orange", "juniper,cyclamen,clary_sage,iris", "tobacco,sandalwood,vanilla,amber",
     "dreamy,Italian,masculine,artistic,floral"),
    ("Versace Gianni Versace",     "Versace","oriental_woody",
     "bergamot,galbanum,aldehydes", "rose,jasmine,ylang_ylang,tuberose", "sandalwood,vetiver,civet,oakmoss,amber",
     "baroque,iconic,bold,Italian,opulent"),
    ("Versace Pour Femme Dylan Turquoise","Versace","floral_fruity",
     "watermelon,mandarin,passion_fruit", "jasmine,cyclamen,rose", "musk,guaiac_wood,patchouli",
     "turquoise,summer,beach,fresh,feminine"),
    # ── GIVENCHY ────────────────────────────────────────────────────────────
    ("Givenchy L Interdit",        "Givenchy","floral_gourmand",
     "pear,bergamot,pink_pepper", "jasmine,tuberose,orange_blossom", "patchouli,vetiver,white_musk",
     "forbidden,dark,floral,modern,audrey"),
    ("Givenchy Ange ou Demon",     "Givenchy","floral_woody",
     "aldehydes,bergamot,lemon", "magnolia,white_flowers,oak,licorice", "sandalwood,musk,styrax,woods",
     "angel,demon,duality,feminine,dramatic"),
    ("Givenchy Irresistible",      "Givenchy","floral_musky",
     "bergamot,pink_pepper", "rose,peony", "white_musk,sandalwood,ambroxan",
     "irresistible,rose,feminine,fresh,modern"),
    ("Givenchy Gentleman Only",    "Givenchy","aromatic_woody",
     "bergamot,lemon,vetiver", "cardamom,iris,cedar", "leather,patchouli,vetiver",
     "elegant,gentleman,modern,woody"),
    ("Givenchy Pi",                "Givenchy","oriental_fougere",
     "bergamot,mandarin", "elemi,geranium,rose,jasmine,anise", "sandalwood,vanilla,amber,tonka_bean",
     "intellectual,mathematical,masculine,warm"),
    ("Givenchy Very Irresistible",  "Givenchy","floral_fruity",
     "pink_pepper,star_anise", "rose,peony,magnolia", "white_musk,amber,sandalwood",
     "irresistible,feminine,vibrant,rose,modern"),
    # ── PRADA ───────────────────────────────────────────────────────────────
    ("Prada Infusion d Iris",      "Prada","floral",
     "mandarin,galbanum,bergamot", "iris,orange_blossom,cedar,cedar,rose,vetiver", "sandalwood,benzyl_benzoate,white_musk",
     "minimalist,Italian,iris,clean,pure"),
    ("Prada Candy",                "Prada","oriental_gourmand",
     "caramel", "benzoin,beeswax", "white_musk,musks",
     "sweet,addictive,sophisticated,candy"),
    ("Prada L Homme",              "Prada","aromatic_fougere",
     "iris,neroli,mandarin", "geranium,amber,sandalwood", "white_musk",
     "masculine,modern,Italian,clean"),
    ("Prada La Femme",             "Prada","floral",
     "bergamot,aldehydes", "tuberose,ylang_ylang,iris", "sandalwood,vanilla,amber",
     "Italian,feminine,rich,tuberose"),
    ("Prada Amber",                "Prada","oriental_fougere",
     "bergamot,neroli,mandarin,orange", "patchouli,labdanum,sandalwood,coumarin,geranium", "amber,tonka_bean,leather,musk,vanilla",
     "amber,Italian,warm,classic"),
    ("Prada Paradoxe",             "Prada","floral",
     "bergamot,orange,neroli", "jasmine,musk,amber", "sandalwood,white_musk",
     "paradox,modern,feminine,floral,Italian"),
    # ── LANCOME ─────────────────────────────────────────────────────────────
    ("Lancome La Vie est Belle",   "Lancome","floral_gourmand",
     "grapefruit,blackcurrant,pear", "iris,jasmine,orange_blossom", "praline,patchouli,vanilla,tonka_bean",
     "happy,optimistic,sweet,feminine,iconic"),
    ("Lancome La Nuit Tresor",     "Lancome","oriental_floral",
     "bergamot,citrus,raspberry,blackberry", "jasmine,turkish_rose,rose", "caramel,blackberry,praline,patchouli,vanilla",
     "nocturnal,sweet,dark,romantic,red"),
    ("Lancome Tresor",             "Lancome","floral_oriental",
     "bergamot,aldehydes", "rose,lilac,iris,heliotrope,jasmine", "sandalwood,amber,musk,vanilla,peach",
     "classic,romantic,French,feminine,timeless"),
    ("Lancome Miracle",            "Lancome","floral_fruity",
     "lychee,magnolia,freesia", "jasmine,ginger,rose", "white_musk,sandalwood,amber",
     "fresh,miracle,optimistic,feminine,bright"),
    ("Lancome Idole",              "Lancome","floral",
     "pear,bergamot", "rose,jasmine", "vanilla,musk,cashmeran",
     "idol,modern,feminine,rose,bold"),
    # ── CALVIN KLEIN ────────────────────────────────────────────────────────
    ("CK One",                     "Calvin Klein","citrus_aromatic",
     "bergamot,lemon,green_tea,pineapple,papaya", "rose,jasmine,lily_of_the_valley,violet,nutmeg", "amber,sandalwood,musk,cedar,oakmoss",
     "fresh,clean,unisex,90s,minimal,iconic"),
    ("CK Eternity",                "Calvin Klein","floral_green",
     "freesia,bergamot,marigold,sage", "sandalwood,narcissus,lily_of_the_valley,jasmine,rose", "amber,sandalwood,musk,cedarwood",
     "timeless,clean,feminine,classic,romantic"),
    ("CK Obsession",               "Calvin Klein","oriental",
     "bergamot,aldehydes,tangerine", "jasmine,spices,orange,rose", "vanilla,amber,musk,civet,sandalwood",
     "obsession,dark,80s,bold,controversial"),
    ("CK Euphoria",                "Calvin Klein","floral_oriental",
     "pomegranate,persimmon,green_notes", "lotus,black_orchid,champaca", "mahogany,black_violet,amber,sandalwood,musk",
     "euphoria,dark,floral,feminine,sensual"),
    ("CK Escape",                  "Calvin Klein","floral_fruity",
     "mandarin,bergamot,plum,peach,marigold", "jasmine,rose,lily,magnolia,clove", "sandalwood,cedarwood,amber,musk",
     "tropical,escape,fresh,summery,joyful"),
    # ── DOLCE & GABBANA ──────────────────────────────────────────────────────
    ("D&G Light Blue",             "D&G","fresh_fruity",
     "grapefruit,lemon,apple,bellflower", "jasmine,bamboo,white_rose,marigold", "cedar,musk,amber",
     "mediterranean,fresh,summer,light,iconic"),
    ("D&G The One",                "D&G","oriental_floral",
     "grapefruit,bergamot,coriander,mandarin", "ginger,cardamom,jasmine,orange_blossom", "amber,sandalwood,musk,patchouli,vanilla",
     "The_One,glamorous,feminine,warm,opulent"),
    ("D&G The One Man",            "D&G","oriental_woody",
     "grapefruit,coriander,basil", "ginger,orange_blossom,cardamom,tobacco", "amber,cedar,sandalwood,vetiver",
     "masculine,sophisticated,Italian,warm,tobacco"),
    ("D&G Pour Femme",             "D&G","floral",
     "raspberry,bergamot,neroli", "rose,magnolia,jasmine", "sandalwood,vanilla,musk,amber",
     "Italian,feminine,floral,warm,romantic"),
    ("D&G Pour Homme Intenso",     "D&G","woody_aromatic",
     "bergamot,labdanum,tobacco", "gaiac_wood,neroli,sandalwood", "amber,tobacco,musk,vanilla",
     "intense,Italian,warm,masculine,tobacco"),
    # ── BURBERRY ────────────────────────────────────────────────────────────
    ("Burberry Her",               "Burberry","fruity_floral",
     "strawberry,violet,blackcurrant,red_berries", "jasmine,violet,rose", "amber,vanilla,musk",
     "british,modern,feminine,berry"),
    ("Burberry Brit",              "Burberry","oriental_fruity",
     "bergamot,lemon,almond", "magnolia,peony,amber_rose,cardamom", "tonka_bean,amber,sandalwood,musk",
     "british,warm,sweet,feminine"),
    ("Burberry Weekend",           "Burberry","floral_citrus",
     "lemon,bergamot,pink_pepper", "white_rose,white_magnolia,white_peony", "amber,sandalwood,white_musk",
     "british,fresh,weekend,countryside"),
    ("Burberry London",            "Burberry","chypre_floral",
     "bergamot,green_tea,petitgrain", "peony,heliotrope,rose", "musk,sandalwood,oakmoss",
     "british,classic,foggy,heritage"),
    # ── MARC JACOBS ─────────────────────────────────────────────────────────
    ("Marc Jacobs Daisy",          "Marc Jacobs","floral",
     "strawberry,violet_leaves,grapefruit", "jasmine,gardenia,violet", "white_musk,sandalwood,vanilla",
     "youthful,fresh,innocent,spring,iconic"),
    ("Marc Jacobs Daisy Dream",    "Marc Jacobs","floral_fruity",
     "blackberry,grapefruit,pear", "jasmine,lychee,wisteria,coconut", "white_musk,cedarwood,vanilla",
     "dreamy,airy,feminine,young"),
    ("Marc Jacobs Honey",          "Marc Jacobs","floral_fruity",
     "pear,pink_pepper,tangerine", "honeysuckle,peach,orange_blossom", "honey,apricot,vanilla,white_musk",
     "sweet,honey,cheerful,feminine,playful"),
    # ── PACO RABANNE ─────────────────────────────────────────────────────────
    ("Paco Rabanne 1 Million",     "Paco Rabanne","fresh_spicy",
     "grapefruit,mint,blood_orange", "rose,cinnamon,spices", "leather,amber,white_musk",
     "opulent,spicy,golden,seductive,million"),
    ("Paco Rabanne Lady Million",  "Paco Rabanne","floral_chypre",
     "bitter_orange,raspberry,neroli", "rose,jasmine,gardenia", "patchouli,honey,amber",
     "million,luxe,feminine,golden,rich"),
    ("Paco Rabanne Invictus",      "Paco Rabanne","fresh_marine",
     "grapefruit,sea_notes,blood_mandarin", "bay_leaf,jasmine,hedione", "guaiac_wood,oakmoss,amber",
     "victory,masculine,fresh,sport,champion"),
    ("Paco Rabanne Olympea",       "Paco Rabanne","floral_oriental",
     "green_tangerine,ginger", "jasmine,peony", "sand_accord,cashmere_wood,vanilla",
     "olympia,goddess,feminine,powerful,warm"),
    ("Paco Rabanne XS Pour Homme","Paco Rabanne","oriental_fougere",
     "bergamot,grapefruit,apple", "rose,jasmine,basil", "sandalwood,vetiver,amber,tonka_bean",
     "excess,masculine,seductive,cool,dark"),
    # ── JEAN PAUL GAULTIER ───────────────────────────────────────────────────
    ("JPG Le Male",                "Jean Paul Gaultier","oriental_fougere",
     "cardamom,bergamot,mint", "cinnamon,cumin,lavender,orange_blossom", "vanilla,sandalwood,cedar,amber",
     "sensual,masculine,sailor,iconic,body"),
    ("JPG Classique",              "Jean Paul Gaultier","floral_oriental",
     "rose,orange_blossom,pear,honey", "iris,jasmine,ginger,ylang_ylang,rose,ginger", "sandalwood,amber,vanilla,musk",
     "feminine,iconic,corset,French,sweet"),
    ("JPG Scandal",                "Jean Paul Gaultier","oriental_floral",
     "blood_orange", "gardenia,honey", "patchouli,amber,vetiver",
     "scandal,bold,honey,feminine,night"),
    ("JPG Ultra Male",             "Jean Paul Gaultier","oriental_fougere",
     "mint,bergamot,cardamom", "lavender,cumin,cinnamon", "vanilla,amber,musk",
     "ultra,intense,masculine,seductive,irresistible"),
    # ── AZZARO ───────────────────────────────────────────────────────────────
    ("Azzaro Pour Homme",          "Azzaro","aromatic_fougere",
     "anise,sage,lemon,verbena,bergamot", "rosemary,geranium,basil,jasmine,carnation,lavender", "sandalwood,oakmoss,cedar,amber,vetiver,musk",
     "classic,iconic,fougere,masculine,aromatic"),
    ("Azzaro Chrome",              "Azzaro","aromatic_aquatic",
     "lemon,bergamot,rosemary", "coriander,oakmoss,jasmine", "tonka_bean,cedar,sandalwood",
     "fresh,masculine,sporty,mediterranean"),
    ("Azzaro Wanted",              "Azzaro","oriental_woody",
     "lemon,cardamom,grapefruit", "iris,vetiver,pink_pepper,cumin", "cedarwood,amber,benzoin",
     "wanted,bold,masculine,western,daring"),
    # ── LATTAFA ──────────────────────────────────────────────────────────────
    ("Lattafa Khamrah",            "Lattafa","oriental_gourmand",
     "cinnamon,black_pepper,saffron", "oud,rose,labdanum", "vanilla,amber,leather,frankincense",
     "arabic,spicy,warm,night,oud"),
    ("Lattafa Oud For Glory",      "Lattafa","oriental_woody",
     "saffron,bergamot,cardamom", "oud,rose,patchouli", "amber,leather,sandalwood,musk",
     "oud,glory,arabic,powerful,dark"),
    ("Lattafa Ameer Al Oud",       "Lattafa","oriental_woody",
     "bergamot,cardamom,pink_pepper", "oud,rose,saffron,musk", "amber,patchouli,sandalwood",
     "prince,oud,arabic,royal,rich"),
    ("Lattafa Asad",               "Lattafa","aromatic_fougere",
     "bergamot,lemon,green_apple,pineapple", "lavender,jasmine,rose,geranium", "amber,oakmoss,sandalwood,musk,patchouli",
     "lion,fresh,affordable,clean"),
    ("Lattafa Raghba",             "Lattafa","oriental_gourmand",
     "amber,vanilla,cinnamon", "oud,leather,patchouli", "vanilla,amber,musk,sandalwood",
     "arabic,sweet,oud,warm,affordable"),
    ("Lattafa Yara",               "Lattafa","floral_fruity",
     "bergamot,mandarin,pink_pepper", "peach,rose,jasmine,freesia", "musk,ambroxan,sandalwood,vanilla",
     "young,feminine,fruity,fresh,arabic"),
    # ── RASASI ───────────────────────────────────────────────────────────────
    ("Rasasi La Yuqawam Man",      "Rasasi","oriental_woody",
     "grapefruit,bergamot,cardamom", "oud,sandalwood,rose,amber", "musk,amber,leather",
     "arabic,oud,powerful,masculine,irresistible"),
    ("Rasasi Hawas",               "Rasasi","fresh_aromatic",
     "mint,bergamot,lemon,cardamom", "aquatic,geranium,lavender", "amberwood,musk,patchouli,sandalwood",
     "fresh,desire,aquatic,masculine,affordable"),
    ("Rasasi Egra",                "Rasasi","floral_fruity",
     "bergamot,apple,peach", "jasmine,rose,peony", "musk,amber,sandalwood,vanilla",
     "feminine,fruity,arabic,fresh"),
    # ── ZIMAYA / AFNAN / ARMAF ───────────────────────────────────────────────
    ("Zimaya Fakhama White",       "Zimaya","floral_oriental",
     "bergamot,mandarin", "rose,jasmine,lily_of_the_valley", "sandalwood,amber,vanilla,musk",
     "arabic,white,elegant,oud,affordable"),
    ("Afnan 9 PM",                 "Afnan","oriental_woody",
     "bergamot,apple,cardamom", "jasmine,cinnamon,patchouli", "vanilla,amber,musk,sandalwood",
     "PM,dark,seductive,affordable,arabic"),
    ("Armaf Club de Nuit Intense","Armaf","fruity_chypre",
     "lemon,pineapple,apple,blackcurrant", "rose,jasmine,birch,cardamom", "musk,ambergris,vanilla,sandalwood",
     "affordable,classy,fresh,fruity,masculne"),
    ("Armaf Club de Nuit Women","Armaf","fruity_floral",
     "lychee,peach,bergamot", "rose,jasmine,lily_of_the_valley", "musk,sandalwood,amber,vanilla",
     "feminine,fruity,fresh,affordable,floral"),
    # ── NICHE INDEPENDENTS ───────────────────────────────────────────────────
    ("Escentric Molecules Molecule 01","EM","woody",
     "iso_e_super", "iso_e_super", "iso_e_super",
     "synthetic,skin,invisible,cult,minimalist"),
    ("Escentric Molecules Molecule 04","EM","floral_musky",
     "javanol", "javanol", "javanol",
     "sandalwood,skin,clean,modern,unique"),
    ("Juliette Has A Gun Not a Perfume","JHAG","musk",
     "ambrette", "ambrette", "ambrette",
     "minimal,skin,signature,unique,not_perfume"),
    ("Juliette Has A Gun Romantina","JHAG","floral_fruity",
     "rose,peach,lychee", "patchouli,amber", "vanilla,musk,cedarwood",
     "romantic,rose,feminine,playful,fun"),
    ("Nasomatto Black Afgano",     "Nasomatto","oriental_woody",
     "cannabis,oud,incense", "oud,coffee,tobacco", "resin,musk,oud",
     "dark,underground,narcotic,cannabis,extreme"),
    ("Nasomatto Absinth",          "Nasomatto","green_aromatic",
     "absinthe,galbanum,green", "vetiver,styrax,sage", "resin,musk,wood",
     "wormwood,green,dark,extreme,provocative"),
    ("Zoologist Bee",              "Zoologist","floral_gourmand",
     "osmanthus,honey,beeswax,yuzu", "rose,chamomile,carnation", "benzoin,labdanum,musk,ambergris",
     "bee,honey,nature,artisan,unique"),
    ("Zoologist Tyrannosaurus Rex","Zoologist","green_earthy",
     "green,soil,pine,petrichor", "vetiver,oakmoss,cedar", "labdanum,musk,amber,leather",
     "prehistoric,earthy,primal,artisan"),
    ("Histoires de Parfums 1969",  "HdP","oriental_floral",
     "peach,bergamot,blackcurrant", "rose,jasmine,iris", "patchouli,musk,vanilla,labdanum",
     "1969,peace,love,hippie"),
    ("Histoires de Parfums 1740",  "HdP","oriental",
     "saffron,cardamom,coriander", "tobacco,rose,cinnamon", "amber,benzoin,vetiver,sandalwood",
     "marquis,baroque,dark,historical,tobacco"),
    ("Tauer Perfumes Lonestar Memories","Tauer","leather_woody",
     "bergamot,petitgrain,pink_pepper", "leather,suede,birch_tar", "vetiver,sandalwood,labdanum,oakmoss",
     "americana,leather,campfire,solitary,artisan"),
    ("Olfactive Studio Panorama",  "OS","woody_aromatic",
     "bergamot,lemon", "vetiver,cedar", "musk,ambrette",
     "minimalist,photography,woody,fresh"),
    ("Vilhelm Parfumerie Dear Polly","VP","floral_fruity",
     "bergamot,green_apple", "rose,peony,raspberry", "musk,cedar,sandalwood",
     "playful,berry,romantic,danish"),
    ("Memo Paris Irish Leather",   "Memo Paris","leather_floral",
     "bergamot,pink_pepper,grapefruit", "iris,rose,geranium", "leather,ambroxan,cedar,musk",
     "ireland,fresh,leather,adventure"),
    ("Nishane Hundred Silent Ways","Nishane","floral_woody",
     "bergamot,rose,saffron", "oud,patchouli,sandalwood", "amber,leather,musk",
     "turkish,opulent,complex,art"),
    ("Nishane Ani",                "Nishane","floral_fruity",
     "yuzu,raspberry,marigold", "rose,jasmine,magnolia", "sandalwood,amber,musk",
     "Turkish,light,joyful,feminine"),
    ("Kilian Black Phantom",       "Kilian","oriental_gourmand",
     "rum,black_coffee", "sugar,jasmine", "leather,patchouli,sandalwood",
     "dark,rum,gothic,seductive"),
    ("Kilian Love",                "Kilian","floral_oriental",
     "bergamot,lemon", "peony,jasmine,rose", "white_musk,amber,sandalwood",
     "love,feminine,luxurious,romantic"),
    ("Kilian Good Girl Gone Bad",  "Kilian","floral",
     "pink_pepper,bergamot", "rose,tuberose,jasmine,ylang_ylang", "sandalwood,musk,vetiver",
     "good_girl,bad,floral,seductive,fresh"),
    ("Xerjoff Naxos",              "Xerjoff","oriental_gourmand",
     "bergamot,lemon", "jasmine,honey,cinnamon", "tonka_bean,tobacco,vanilla,amber",
     "tuscan,honey,warm,sophisticated"),
    ("Xerjoff Erba Pura",          "Xerjoff","floral_fruity",
     "bergamot,lemon,orange,mandarin", "white_musk,jasmine,peach,freesia", "ambergris,cedarwood,musk",
     "pure,summery,Mediterranean,Italian,clean"),
    ("Xerjoff Alexandria II",      "Xerjoff","oriental_floral",
     "bergamot,rose,mandarin", "jasmine,rose,incense,patchouli", "sandalwood,oud,amber,vanilla",
     "alexander,opulent,oriental,historical"),
    ("Clive Christian No 1",       "Clive Christian","floral_oriental",
     "cardamom,bergamot,pink_pepper", "ylang_ylang,rose,heliotrope", "sandalwood,amber,musk,oud",
     "luxurious,expensive,floral,iconic"),
    ("Roja Dove Elysium",          "Roja Dove","citrus_aquatic",
     "bergamot,lemon,orange,grapefruit,lime", "geranium,marine,angelica", "sandalwood,musk,amber",
     "luminous,clean,fresh,masterpiece"),
    ("Roja Dove Scandal",          "Roja Dove","floral_oriental",
     "bergamot,aldehydes,ylang_ylang", "rose,jasmine,lily,iris", "sandalwood,civet,amber,musk,vanilla",
     "scandalous,opulent,classic,iconic,luxury"),
    ("Initio Atomic Rose",         "Initio","floral",
     "pink_pepper", "rose,ambrette", "ambroxan,vanilla,white_musk",
     "modern,aphrodisiac,rose,daring"),
    ("Initio Side Effect",         "Initio","oriental_woody",
     "rum,vanilla,cardamom", "ambroxan,musk", "sandalwood,vetiver,amber",
     "addictive,dark,rum,warm,masculine"),
    ("Initio Psychedelic Love",    "Initio","floral_woody",
     "saffron,bergamot,pink_pepper", "rose,peony,patchouli", "ambroxan,musk,sandalwood",
     "love,psychedelic,modern,bold"),
    ("Parfums de Marly Layton",    "PdM","floral_woody",
     "apple,bergamot,lavender", "geranium,jasmine,violet", "sandalwood,vanilla,guaiac_wood,pepper",
     "elegant,french,masculine,rich"),
    ("Parfums de Marly Percival",  "PdM","fresh_floral",
     "bergamot,marine,lemon", "lavender,iris,amber", "musk,sandalwood,vetiver",
     "fresh,crisp,masculine,elegant"),
    ("Parfums de Marly Delina",    "PdM","floral",
     "lychee,rhubarb,pink_pepper", "Turkish_rose,peony,jasmine,gardenia", "musk,cashmere_wood,vanilla",
     "rose,feminine,Paris,luxurious,romantic"),
    ("Parfums de Marly Herod",     "PdM","oriental_woody",
     "bergamot,cardamom,pink_pepper", "tobacco,osmanthus,amber", "vanilla,cedar,sandalwood",
     "herod,dark,tobacco,warm,masculine"),
    ("Montale Black Aoud",         "Montale","oriental_woody",
     "rose,pink_pepper", "oud,musk,patchouli", "amber,rose,musk",
     "oud,rose,dark,arabic,powerful"),
    ("Montale Roses Musk",         "Montale","floral_musky",
     "rose,pink_pepper", "rose,amber", "white_musk,sandalwood,cedar",
     "rose,musky,romantic,feminine"),
    ("Montale Intense Cafe",       "Montale","oriental_gourmand",
     "coffee,rose", "coffee,vanilla,rose", "sandalwood,musk,amber",
     "coffee,rose,romantic,sweet,oriental"),
    ("Mancera Cedrat Boise",       "Mancera","fresh_woody",
     "bergamot,lemon,mandarin,black_currant", "jasmine,rose,peach,apple", "cedar,sandalwood,patchouli,musk,ambergris,vanilla",
     "fresh,citrus,elegant,dubai"),
    ("Mancera Aoud Exclusif",      "Mancera","oriental_woody",
     "saffron,bergamot,aldehydes", "oud,rose,jasmine", "amber,musk,sandalwood",
     "oud,exclusive,arabic,opulent"),
    ("Bvlgari Omnia",              "Bvlgari","woody_floral",
     "bergamot,orange,mandarin", "indian_tea,cardamom,wood", "sandalwood,guaiac_wood,heliotrope",
     "india,meditation,wood,warm,spicy"),
    ("Bvlgari Omnia Crystalline",  "Bvlgari","floral_woody",
     "bamboo,nymphea,cassia", "lotus,algae,balsa_wood", "white_musk",
     "crystal,pure,transparent,floral"),
    ("Bvlgari Man in Black",       "Bvlgari","oriental_spicy",
     "rum,agarwood,spicy_rum", "leather,tuberose,iris,black_orchid", "benzoin,guaiac_wood,amber",
     "black,masculine,dark,oriental,rum"),
    ("Bvlgari Goldea",             "Bvlgari","floral_musky",
     "bergamot,lemon", "rose,jasmine,heliotrope", "sandalwood,musk,white_musk",
     "gold,feminine,Rome,goddess,luxurious"),
    ("Acqua di Parma Colonia",     "AdiP","citrus",
     "lemon,bergamot,orange,lavender", "rose,jasmine,vetivert", "vetiver,sandalwood,musk,oakmoss",
     "classic,refined,italian,elegant,heritage"),
    ("Acqua di Parma Magnolia Nobile","AdiP","floral",
     "bergamot,neroli,petitgrain", "magnolia,ylang_ylang,jasmine,rose", "sandalwood,white_musk,cedarwood",
     "italian,magnolia,feminine,elegant,spring"),
    ("Acqua di Parma Blu Mediterraneo","AdiP","fresh_citrus",
     "lemon,mandarin,bergamot", "sweet_basil,petitgrain", "musk,white_musk",
     "mediterranean,fresh,italian,amalfi,coastal"),
    ("L Artisan Parfumeur Passage d Enfer","L Artisan","incense_floral",
     "lily,green_notes,watery", "incense,white_flowers", "cedar,musk,sandalwood",
     "incense,church,spiritual,poetic"),
    ("L Artisan Parfumeur Mure et Musc","L Artisan","fruity_musky",
     "blackberry,bergamot,lemon", "rose,blackberry", "musk,white_musk,sandalwood",
     "blackberry,musky,fresh,feminine"),
    ("L Artisan Parfumeur Tea for Two","L Artisan","oriental_gourmand",
     "bergamot,black_tea", "cinnamon,ginger,honey", "vanilla,amber,musk,sandalwood",
     "tea,fireside,cozy,spicy,warm"),
    ("Comme des Garcons Wonderwood","CdG","woody",
     "cypress,pine", "guaiac_wood,sandalwood,cedarwood", "patchouli,musk",
     "japan,minimalist,woody,zen"),
    ("Comme des Garcons Incense Kyoto","CdG","incense",
     "hinoki,cypress,woody", "incense,frankincense", "benzoin,musk,cedar",
     "kyoto,zen,Japanese,incense,temple"),
    ("Comme des Garcons 2 Man",    "CdG","green_aromatic",
     "galbanum,magnolia,aldehydes", "iris,lily,jasmine", "sandalwood,amber,musk,cedar",
     "conceptual,avant_garde,green,masculine"),
    ("Issey Miyake L Eau d Issey","Issey Miyake","floral_aquatic",
     "rose_water,lotus,calone,cyclamen,freesia", "peony,lily,aquatics", "sandalwood,musk,amber",
     "water,zen,Japanese,minimalist"),
    ("Issey Miyake L Eau d Issey Pour Homme","Issey Miyake","aromatic_aquatic",
     "yuzu,calone,lemon,cyclamen", "coriander,nutmeg,lily_of_the_valley,geranium", "sandalwood,amber,musk,tobacco",
     "zen,fresh,aquatic,Japanese,masculine"),
    ("Thierry Mugler Angel",       "Mugler","oriental_gourmand",
     "bergamot,mandarin", "honey,jasmine,caramel", "vanilla,chocolate,patchouli,tonka_bean",
     "gourmand,sweet,daring,iconic,revolutionary"),
    ("Thierry Mugler Alien",       "Mugler","floral_woody",
     "jasmine,airy_note", "jasmine,solar_wood", "white_amber,sandalwood,cashmeran",
     "alien,otherworldly,feminine,white,solar"),
    ("Rabanne Phantom",            "Paco Rabanne","aromatic_woody",
     "lemon,lavender,patchouli", "hawthorn,vetiver", "benzaldehyde,oakmoss,sandalwood",
     "robot,futuristic,fresh,masculine,innovative"),
    ("Narciso Rodriguez For Her",  "Narciso Rodriguez","floral_musk",
     "rose,peach", "rose,jasmine,peony", "musk,sandalwood,cedar",
     "sensual,modern,understated,feminine"),
    ("Narciso Rodriguez Musc Noir Rose","Narciso Rodriguez","floral_musky",
     "pink_pepper,bergamot", "rose,musk", "white_musk,sandalwood",
     "musky,rose,modern,dark,feminine"),
    ("Viktor Rolf Flowerbomb",     "Viktor & Rolf","floral_oriental",
     "bergamot,tea", "rose,jasmine,peony,freesia", "patchouli,vanilla,amber",
     "explosive,opulent,romantic,feminine"),
    ("Viktor Rolf SpiceBomb",      "Viktor & Rolf","oriental_spicy",
     "bergamot,grapefruit,pink_pepper", "cinnamon,elemi,vetiver", "tobacco,leather,sandalwood",
     "bomb,spicy,masculine,explosive,daring"),
    ("Carolina Herrera 212",       "CH","floral",
     "bergamot,peach,magnolia,freesia", "lily_of_the_valley,jasmine,tuberose", "sandalwood,amber,musk",
     "NYC,fresh,modern,feminine,urban"),
    ("Carolina Herrera Good Girl", "CH","floral_oriental",
     "lemon,pink_pepper,coffee", "jasmine,tuberose,white_flowers", "cocoa,cacao,sandalwood,cedar,vanilla",
     "good_girl,dark,feminine,duality,iconic"),
    ("Valentino Valentina",        "Valentino","white_floral",
     "lime,jasmine", "tuberose,lily", "sandalwood,white_musk,iris",
     "glamorous,Italian,feminine,white"),
    ("Valentino Donna Born in Roma","Valentino","floral_woody",
     "grapefruit,pink_pepper,neroli", "jasmine,vetiver,ambrette", "sandalwood,cashmere_wood,vanilla",
     "Rome,Italian,feminine,modern"),
    ("Gucci Bloom",                "Gucci","floral",
     "white_tea", "tuberose,jasmine,rangoon_creeper", "sandalwood,white_musk",
     "garden,white,lush,feminine"),
    ("Gucci Flora",                "Gucci","floral",
     "pink_pepper,citrus,rose", "peony,rose,osmanthus", "sandalwood,patchouli,amber",
     "flora,garden,Italian,feminine,fresh"),
    ("Gucci Guilty",               "Gucci","oriental_floral",
     "pink_pepper,mandarin,lilac", "geranium,lilac,jasmine", "amber,cedar,patchouli",
     "guilty,daring,feminine,modern,Italian"),
    ("Gucci Bamboo",               "Gucci","floral_woody",
     "yuzu,bergamot,pink_pepper", "rose,ylang_ylang,casablanca_lily", "sandalwood,amber,cedarwood",
     "bamboo,fresh,feminine,natural,Italian"),
    ("Jimmy Choo EDP",             "Jimmy Choo","floral_fruity",
     "pear,pink_pepper,mandarin_blossom", "tiger_lily,orchid,jasmine", "patchouli,amber,sandalwood,toffee_wood",
     "shoes,feminine,sexy,playful,fruity"),
    ("Michael Kors Gorgeous",      "Michael Kors","floral_musky",
     "lychee,grapefruit,pink_pepper", "rose,peony,lily_of_the_valley,magnolia", "amber,sandalwood,white_musk",
     "gorgeous,feminine,radiant,fresh"),
    ("Coach Dreams",               "Coach","floral_fruity",
     "pear,bergamot", "lily_of_the_valley,coconut_water", "amber,cedarwood,musk",
     "american,dream,fresh,feminine,optimistic"),
    ("Ralph Lauren Polo Blue",     "Ralph Lauren","fresh_aromatic",
     "melon,cucumber,sage", "suede,basil,geranium,mango", "vetiver,suede,sandalwood,amber",
     "polo,american,fresh,sporty,sky"),
    ("Ralph Lauren Romance",       "Ralph Lauren","floral",
     "marigold,bergamot,chamomile", "rose,magnolia,jasmine,iris", "amber,sandalwood,musk,patchouli",
     "romance,american,feminine,classic,floral"),
    ("Davidoff Cool Water",        "Davidoff","aromatic_aquatic",
     "lavender,green_notes,marine,bergamot,coriander", "jasmine,geranium,rosemary,neroli,sandalwood", "cedarwood,sandalwood,amber,musk,oakmoss",
     "water,cool,fresh,iconic,masculine"),
    ("Davidoff The Game",          "Davidoff","woody_spicy",
     "grapefruit,black_pepper", "rose,patchouli,iris", "guaiac_wood,vetiver,sandalwood",
     "game,masculine,strong,fresh"),
    ("Dolce Gabbana The Only One", "D&G","floral_gourmand",
     "coffee,violet,bergamot", "rose,cashmere_musk", "amber,musks,vanilla",
     "the_one,feminine,modern,Italian,warm"),
    ("Bulgari Aqva",               "Bvlgari","aromatic_aquatic",
     "bergamot,posidonia,marine", "trident_of_neptune,seaweed", "musk,petrol_wood",
     "water,sea,masculine,fresh,roman"),
    ("Bottega Veneta Knot",        "Bottega Veneta","floral_chypre",
     "bergamot,neroli,bitter_orange", "rose,orris,jasmine,tuberose", "vetiver,sandalwood,patchouli",
     "Italian,leather,craftsmanship,feminine,luxurious"),
    ("Balenciaga Paris",           "Balenciaga","floral",
     "green,violet_leaf,pink_pepper", "rose,violet,jasmine,cedar", "musk,amber",
     "paris,minimalist,fashion,feminine,modern"),
    ("Alexander McQueen Kingdom", "Alexander McQueen","floral_woody",
     "bergamot,tuberose,jasmine,peach", "tuberose,jasmine,rose,ylang_ylang", "amber,sandalwood,civet",
     "kingdom,dark,sensual,daring,feminine"),
    ("Missoni Missoni",            "Missoni","floral_oriental",
     "bergamot,mandarin,aldehydes,green_notes", "rose,iris,jasmine", "patchouli,amber,musk,vanilla",
     "Italian,fashion,colourful,feminine,warm"),
    ("Issey Miyake Nuit d Issey",  "Issey Miyake","oriental_woody",
     "bergamot,cedar", "leather,papyrus,amber_wood", "vetiver,ebony,musk",
     "night,Japanese,masculine,minimalist,dark"),
    ("Rochas Femme",               "Rochas","chypre_floral",
     "peach,aldehydes,bergamot", "rose,jasmine,ylang_ylang,lily_of_the_valley,iris", "sandalwood,vetiver,oakmoss,musk,civet",
     "classic,French,feminine,peach,chypre"),
    ("Givenchy Amarige",           "Givenchy","floral_oriental",
     "mandarin,violet,bergamot", "tuberose,rose,gardenia,ylang_ylang,mimosa", "sandalwood,amber,civet,musk,vanilla",
     "floral,bold,feminine,French,white"),
    ("Chloe EDP",                  "Chloe","floral",
     "peony,lychee,freesia", "rose,lily_of_the_valley,magnolia", "cedar,Virginia_cedar,musk",
     "feminine,romantic,fresh,French,delicate"),
    ("Chloe Nomade",               "Chloe","floral_woody",
     "freesia,oak", "jasmine,rose,mirabelle", "oak,musk,cashmere_wood,patchouli",
     "nomade,free,feminine,French,woody"),
    ("Donna Karan DKNY Be Delicious","DKNY","floral_fruity",
     "apple,grapefruit,cucumber,violet_leaf", "rose,magnolia,white_muguet,jasmine", "sandalwood,blonde_woods,musk,oakmoss",
     "new_york,apple,fresh,feminine,urban"),
    ("Michael Kors Michael",       "Michael Kors","floral_fruity",
     "tangerine,litchi,cardamom", "magnolia,jasmine,white_peach", "patchouli,sandalwood,amber,musk",
     "american,glamorous,feminine,warm"),
    ("Stella McCartney Stella",    "Stella McCartney","floral",
     "rose,rhubarb,peony,violet", "rose,peony,amber,peach", "cedar,musk,amber",
     "british,eco,rose,feminine,fresh"),
    ("Ferragamo Incanto",          "Ferragamo","floral_fruity",
     "lychee,bergamot,pink_pepper", "peony,jasmine,water_lily", "musk,cedar,sandal",
     "Italian,feminine,fresh,fruity"),
    ("Dolce Gabbana Sicily",       "D&G","oriental_floral",
     "bergamot,orange,mandarin", "jasmine,rose,ylang_ylang", "sandalwood,patchouli,amber,musk",
     "sicilian,Italian,warm,opulent,feminine"),
    ("Dolce Gabbana Velvet Rose",  "D&G","floral",
     "turkish_rose,rose", "rose,peony", "amber,musk,vanilla",
     "rose,luxury,Italian,exclusive"),
    ("Trussardi Donna",            "Trussardi","floral_woody",
     "bergamot,grapefruit,green_notes", "iris,jasmine,rose", "sandalwood,cedar,musk,amber",
     "Italian,feminine,clean,modern"),
    ("Emporio Armani She",         "Armani","floral_fruity",
     "bergamot,mandarin,blackcurrant", "magnolia,cedar,peach_blossom", "sandalwood,cedar,amber,musk",
     "young,feminine,fresh,Italian"),
    ("Hugo Boss The Scent",        "Hugo Boss","oriental_fougere",
     "ginger,osmanthus,maniguette_pepper", "freesia,iris,leather", "vetiver,sandalwood,cocoa",
     "scent,masculine,dark,seductive,boss"),
    ("Hugo Boss Bottled",          "Hugo Boss","woody_aromatic",
     "apple,bergamot,lemon,plum", "geranium,jasmine,cyclamen", "sandalwood,cedar,vetiver,olive_wood",
     "boss,bottle,masculine,clean,iconic"),
    ("Lacoste Essential",          "Lacoste","aromatic_fougere",
     "tomato_leaves,rosewood,bergamot", "rose,jasmine,black_currant_buds,calone", "vetiver,patchouli,sandalwood,leather,musk",
     "sport,fresh,green,masculine,tennis"),
    ("Joop Homme",                 "Joop","oriental",
     "bergamot,honey,orange,lemon,melon,petitgrain", "heliotrope,lily_of_the_valley,jasmine,rose,carnation", "amber,sandalwood,civet,vanilla,musk",
     "sweet,fruity,masculine,90s,oriental"),
    ("Fahrenheit 32",              "Dior","aromatic_woody",
     "hesperides,yuzu", "cedar,cardamom,sandalwood", "vetiver,ambergris,musk",
     "fresh,crisp,masculine,modern"),
    ("Lalique Encre Noire",        "Lalique","woody",
     "vetiver,cypress", "vetiver,encens", "musk,ambrette",
     "vetiver,black,smoky,masculine,artistic"),
    ("Lalique Le Parfum",          "Lalique","floral_oriental",
     "bergamot,pink_pepper,mandarin", "rose,heliotrope,jasmine", "amber,vanilla,labdanum,musk",
     "crystal,feminine,French,luxurious"),
    ("Cartier Declaration",        "Cartier","woody_aromatic",
     "cardamom,cedar,bergamot,juniper", "thyme,rose", "vetiver,sandalwood",
     "cartier,masculine,cedar,elegant"),
    ("Cartier Baiser Vole",        "Cartier","floral",
     "lemon,bergamot,lily_stem", "lily,magnolia,jasmine", "white_musk,lily,cedar",
     "lily,pure,feminine,French,elegant"),
    ("Prada Amber Pour Homme",     "Prada","oriental_fougere",
     "bergamot,neroli,mandarin", "patchouli,labdanum,myrrh,orange_blossom,geranium", "amber,leather,labdanum",
     "Italian,masculine,warm,amber,sophistacted"),
    ("Jean Louis Scherrer Scherrer","JLS","floral_aldehyde",
     "aldehydes,bergamot,rose", "rose,jasmine,ylang_ylang,iris", "sandalwood,amber,civet,oakmoss",
     "classic,French,feminine,aldehyde"),
    ("Balenciaga Florabotanica",   "Balenciaga","floral_green",
     "rosa_centifolia,violet_leaf,pink_pepper", "ambrette,carnation,thorn,green", "amber,vetiver,musk",
     "botanical,green,avant_garde,floral,fashion"),
    ("Byredo Oud Immortel",        "Byredo","woody_oriental",
     "pink_pepper,frankincense", "oud,papyrus,sandalwood", "black_musk,amber,vetiver",
     "oud,dark,immortal,powerful"),
    ("Byredo La Tulipe",           "Byredo","floral",
     "dewy_leaves,hyacinth,cyclamen", "tulip,jasmine", "cedarwood,musk",
     "tulip,spring,fresh,Swedish,white"),
    ("Byredo Inflorescence",       "Byredo","floral",
     "bergamot,magnolia", "peony,peach_blossom,pink_pepper,freesia,jasmine", "white_musk,sandalwood,amber",
     "flower_field,feminine,fresh,spring,light"),
    ("Byredo Rupestre",            "Byredo","woody",
     "bergamot,orris,sage,juniper", "amber,patchouli,cistus", "musk,vetiver,leather",
     "rock,minerals,masculine,outdoors"),
    ("Initio Blessed Baraka",      "Initio","oriental_woody",
     "frankincense,cardamom,bergamot", "oud,saffron,rose", "labdanum,amber,musk",
     "spiritual,holy,blessed,incense,arabic"),
    ("Atelier Cologne Cedre Atlas","Atelier Cologne","woody_floral",
     "bergamot,lemon,pink_pepper", "cedarwood,rose,jasmine", "cedar,musk,sandalwood",
     "atlas,cedar,masculine,traveller"),
    ("Atelier Cologne Trefle Pur", "Atelier Cologne","aromatic_green",
     "bergamot,black_pepper,galbanum", "clover,iris,violet,orris", "white_musk,cedarwood,vetiver",
     "clover,green,fresh,unisex,pure"),
    ("Atelier Cologne Orange Sanguine","Atelier Cologne","citrus",
     "blood_orange,tangerine,geranium", "jasmine,coriander", "white_musk,vetiver",
     "blood_orange,Italian,bright,fresh,citrus"),
    ("Floris Cefiro",              "Floris","citrus_aromatic",
     "lemon,bergamot,neroli,petitgrain", "rose,geranium,cyclamen", "sandalwood,musk,amber",
     "british,royal,heritage,fresh,citrus"),
    ("Floris Santal",              "Floris","oriental_woody",
     "bergamot,saffron", "sandalwood,rose,jasmine", "amber,oud,white_musk",
     "british,royal,sandalwood,heritage,warm"),
    ("Annick Goutal Hadrien",      "Goutal","citrus",
     "lemon,grapefruit,bergamot,lime,mandarin,verbena", "cypress", "white_musk,cedar",
     "Hadrian,roman,Italian,fresh,citrus"),
    ("Annick Goutal Rose Absolue", "Goutal","floral",
     "rose,lychee", "rose,rose_de_mai,bulgarian_rose,turkish_rose", "musk,cedar,sandalwood",
     "rose,feminine,French,romantic,floral"),
    ("Caron Pour un Homme",        "Caron","oriental_fougere",
     "bergamot,lavender,rosemary", "lavender,geranium", "musk,vanilla,amber",
     "classic,fougere,French,masculine,lavender"),
    ("Guerlain Habit Rouge",       "Guerlain","oriental_fougere",
     "bergamot,aldehydes,lemon,citrus", "rose,leather,jasmine,ylang_ylang", "sandalwood,amber,vetiver,vanilla",
     "equestrian,aristocratic,masculine,French,classic"),
    ("Robert Piguet Fracas",       "Robert Piguet","floral",
     "bergamot,gardenia,peach", "tuberose,narcissus,jasmine,rose,iris,violet", "sandalwood,amber,musk,oakmoss,vetiver",
     "tuberose,bombshell,feminine,iconic,powerful"),
    ("Worth Je Reviens",           "Worth","floral_aldehyde",
     "aldehydes,bergamot,grapefruit", "rose,violet,ylang_ylang,jasmine,narcissus,iris", "sandalwood,vetiver,civet,musk,amber",
     "vintage,French,aldehyde,classic"),
    ("Balenciaga Cristobal",       "Balenciaga","oriental",
     "aldehydes,bergamot,lemon", "rose,ylang_ylang,jasmine,geranium,orris", "sandalwood,vetiver,amber,civet,oakmoss",
     "couture,Spanish,feminine,vintage"),
    ("Maison Margiela Replica Flower Market","Maison Margiela","floral_woody",
     "bergamot,pink_pepper,lemon", "rose,peony,freesia,jasmine", "sandalwood,cedar,white_musk",
     "flower_market,fresh,spring,bright"),
    ("Maison Margiela Replica Coffee Break","Maison Margiela","oriental_gourmand",
     "bergamot,orange,cardamom", "creamy_milk,cashew,cloves,nutmeg", "tonka_bean,sandalwood,musk",
     "coffee,cozy,afternoon,warm,sweet"),
    ("Maison Margiela Replica Autumn Vibes","Maison Margiela","woody_oriental",
     "bergamot,vetiver,rum", "birch,labdanum,cedar", "vanilla,musk,sandalwood",
     "autumn,cozy,falling_leaves,warm,woody"),
    ("Nasomatto Duro",             "Nasomatto","woody_aromatic",
     "pepper,citrus", "elemi,incense,geranium", "oud,guaiac_wood,cedarwood,musk",
     "hard,masculine,provocative,dense,dark"),
    ("Nasomatto Pardon",           "Nasomatto","oriental_woody",
     "rum,whisky", "tobacco,leather", "oud,musk,sandalwood,amber",
     "apology,dark,mysterious,masculine,rum"),
    ("Memo Paris African Land",    "Memo Paris","floral_woody",
     "bergamot,cardamom,ginger", "saffron,rose,jasmine", "leather,musk,amber,oud",
     "africa,wild,adventure,travel,opulent"),
    ("Zoologist Panda",            "Zoologist","green_floral",
     "bamboo,yuzu,bergamot", "osmanthus,jasmine,magnolia", "white_musk,sandalwood,amber",
     "panda,china,bamboo,fresh,artisan"),
    ("Zoologist Dragonfly",        "Zoologist","green_aquatic",
     "bergamot,petrichor,green,marine", "iris,violet,peony", "cedar,musk,amber",
     "dragonfly,water,nature,fresh,artisan"),
    ("Bogue Profumo MAAI",         "Bogue","oriental_floral",
     "bergamot,aldehydes", "rose,iris,jasmine,labdanum", "civet,sandalwood,amber,musk,oakmoss",
     "artisan,animalic,chypre,bold,italian"),
    ("Bruno Fazzolari Lampblack",  "Bruno Fazzolari","woody_aromatic",
     "bergamot,soot,smoke", "birch,pine,incense", "musk,amber,sandalwood",
     "brooklyn,ink,dark,artisan,smoke"),
]

# ---------------------------------------------------------------------------
# TIER 2 — Kaggle/HuggingFace loader
# ---------------------------------------------------------------------------
KAGGLE_COLUMNS = {
    "name":        ["Name", "name", "perfume_name", "title"],
    "brand":       ["Brand", "brand", "designer", "house"],
    "family":      ["mainaccord", "family", "category", "accord"],
    "top_notes":   ["Top", "top_notes", "top", "notes_top"],
    "middle_notes":["Middle", "middle_notes", "heart", "notes_middle"],
    "base_notes":  ["Base", "base_notes", "base", "notes_base"],
}

def load_kaggle_csv(path: str) -> list:
    import csv
    rows = []
    with open(path, newline="", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []
        col_map = {}
        for key, candidates in KAGGLE_COLUMNS.items():
            for c in candidates:
                if c in headers:
                    col_map[key] = c
                    break
        for row in reader:
            entry = {}
            for key, col in col_map.items():
                entry[key] = row.get(col, "").strip()
            if entry.get("name"):
                rows.append(entry)
    print(f"Loaded {len(rows)} perfumes from {path}")
    return rows

# ---------------------------------------------------------------------------
# VAD computation
# ---------------------------------------------------------------------------
def compute_vad(top: str, middle: str, base: str, note_emotions: dict) -> tuple:
    notes = [n.strip().lower().replace(" ", "_").replace("-", "_")
             for n in (top + "," + middle + "," + base).split(",") if n.strip()]
    V = A = D = count = 0.0
    for note in notes:
        if note in note_emotions:
            e = note_emotions[note]
            V += e["valence"]; A += e["arousal"]; D += e["dominance"]; count += 1
    if count == 0:
        return 0.5, 0.5, 0.5
    return round(V / count, 3), round(A / count, 3), round(D / count, 3)

# ---------------------------------------------------------------------------
# Main builder
# ---------------------------------------------------------------------------
def build(tier: int = 1, kaggle_csv: str = None):
    base_dir = Path(__file__).parent.parent
    families_path = base_dir / "data" / "note_families.json"
    out_path = base_dir / "data" / "fragrances.csv"

    with open(families_path) as f:
        note_emotions = json.load(f)["emotion_profile"]

    fieldnames = ["id", "name", "brand", "family", "top_notes", "middle_notes",
                  "base_notes", "mood_tags", "valence", "arousal", "dominance", "source"]

    entries = []

    # Tier 1 — built-in curated list
    for i, p in enumerate(PERFUMES):
        name, brand, family, top, middle, base, moods = p
        V, A, D = compute_vad(top, middle, base, note_emotions)
        entries.append({"id": i, "name": name, "brand": brand, "family": family,
                        "top_notes": top, "middle_notes": middle, "base_notes": base,
                        "mood_tags": moods, "valence": V, "arousal": A, "dominance": D,
                        "source": "curated"})

    # Tier 2 — external CSV
    if tier >= 2 and kaggle_csv:
        ext = load_kaggle_csv(kaggle_csv)
        offset = len(entries)
        for i, row in enumerate(ext):
            top    = row.get("top_notes", "")
            middle = row.get("middle_notes", "")
            base   = row.get("base_notes", "")
            V, A, D = compute_vad(top, middle, base, note_emotions)
            entries.append({
                "id": offset + i,
                "name": row.get("name", "Unknown"),
                "brand": row.get("brand", "Unknown"),
                "family": row.get("family", "unknown"),
                "top_notes": top, "middle_notes": middle, "base_notes": base,
                "mood_tags": "",
                "valence": V, "arousal": A, "dominance": D,
                "source": "kaggle"
            })

    # Deduplicate by name
    seen = set()
    deduped = []
    for e in entries:
        key = e["name"].lower().strip()
        if key not in seen:
            seen.add(key)
            deduped.append(e)

    # Re-index
    for i, e in enumerate(deduped):
        e["id"] = i

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(deduped)

    print(f"Built {len(deduped)} perfumes -> {out_path}")
    by_source = {}
    for e in deduped:
        by_source[e["source"]] = by_source.get(e["source"], 0) + 1
    for src, count in by_source.items():
        print(f"  {src}: {count}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--tier", type=int, default=1, choices=[1, 2],
                        help="1=curated only, 2=curated+kaggle CSV")
    parser.add_argument("--kaggle", type=str, default=None,
                        help="Path to Kaggle/HuggingFace fragrance CSV")
    args = parser.parse_args()
    build(tier=args.tier, kaggle_csv=args.kaggle)
